version: "3.8"

services:
    # Backend API
    smart-brain-api:
        container_name: backend-api
        # image: node:16.13.2
        # build allowing us to build the image from the Dockerfile
        build: ./
        command: npm start
        working_dir: /usr/src/smart-brain-api
        environment:
            # POSTGRES_USER: waldner
            # POSTGRES_PASSWORD: secret
            # POSTGRES_DB: smart-brain-docker
            # POSTGRES_HOST: postgres
            POSTGRES_URI: ${POSTGRES_URI}
            REDIS_URI: ${REDIS_URI}
            CLARIFAI_API_KEY: ${CLARIFAI_API_KEY}
            JWT_SECRET: ${JWT_SECRET}
        ports:
            - "3001:3001"
        # allows us to access the file system where the docker container is running
        # host file system can see the changes made in the host machine
        # mounting to the container
        volumes:
            - ./:/usr/src/smart-brain-api

    # Postgres
    postgres:
        # container_name: postgres
        # image: postgres:13
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
        build: ./postgres
        ports:
            - "5432:5432"

    # Redis
    redis:
        image: redis
        ports:
            - "6379:6379"
